# Generated by Django 4.2.7 on 2023-11-25 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
