# Generated by Django 4.2.7 on 2023-11-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
    ]
