# Generated by Django 4.2.7 on 2023-11-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_contract_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
