# Generated by Django 5.0.2 on 2024-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('model', models.CharField(max_length=50, null=True)),
                ('brand', models.IntegerField(default=0)),
                ('category', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('desintext', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('front', models.ImageField(upload_to='uploads/fronts/')),
                ('back', models.ImageField(upload_to='uploads/backs/')),
                ('interior', models.ImageField(upload_to='uploads/interiors/')),
                ('instock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
