# Generated by Django 5.0.2 on 2024-03-18 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.IntegerField(default=0)),
                ('customer', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.PositiveBigIntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('end_date', models.DateField(default=datetime.datetime.today)),
            ],
            options={
                'db_table': 'contract',
            },
        ),
    ]
